# Generated by Django 5.2.3 on 2025-06-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_employerprofile_jobseekerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='experience',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
