# Generated by Django 5.2.3 on 2025-06-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_savedjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='jobtype',
            field=models.CharField(choices=[('parttime', 'PARTTIME'), ('fulltime', 'FULLTIME'), ('internship', 'INTERNSHIP'), ('remote', 'REMOTE')], max_length=20),
        ),
    ]
