# Generated by Django 5.2.3 on 2025-07-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_application_status_job_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], max_length=20),
        ),
    ]
