# Generated by Django 5.2.3 on 2025-07-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_companyreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreview',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyreview',
            name='reply_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
