# Generated by Django 5.2.3 on 2025-07-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_globalotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('seen', 'Seen')], default='pending', max_length=20),
        ),
    ]
