# Generated by Django 5.2.3 on 2025-07-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_employerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='interview_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='interview_venue',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='walkin_drive',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
